---
NAME: Daniel Olds
COURSE: Machine Learning
ASSIGNMENT: Course Project
TITLE: Satisfiability Classification with Convolutional Neural Networks
output: word_document
---

# Set Working Directory: 
```{r}
# Run this outside of the Notebook chunk 
setwd("C:/Users/dmo/Documents/MachineLearning/Project")
```

# Import Libraries: 
```{r}
library(ggplot2)
library(knitr)
library(readr)
library(keras)
library(tensorflow)
library(reticulate)
library(Matrix)
library(tidyverse)
library(fs)
```

# Generate 3-SAT Dataset:
```{r}
# 50/50 Training Testing Split:

# Training Data - 
train_data <- list(sat_1, sat_2, sat_3, sat_4, sat_5, 
            sat_6, sat_7, sat_8, sat_9, sat_10,
            sat_11, sat_12, sat_13, sat_14, sat_15,
            sat_16, sat_17, sat_18, sat_19, sat_20, 
            unsat_1, unsat_2, unsat_3, unsat_4, unsat_5,
            unsat_6, unsat_7, unsat_8, unsat_9, unsat_10,
            unsat_11, unsat_12, unsat_13, unsat_14, unsat_15,
            unsat_16, unsat_17, unsat_18, unsat_19, unsat_20)

# reshape training matrix 
train_data <- as.matrix(train_data)
train_array <- array(data = do.call(cbind, train_data), dim = c(length(train_data), dim(train_data[[1]]), 1)) 

# Training Labels - 
train_label <- replicate(40, 1)
train_label <- t(train_label)
train_label[21:40] = 0
train_label <- t(train_label)
# train_label <- to_categorical(train_label)


# Testing Data - 
test_data <- list(sat_21, sat_22, sat_23, sat_24, sat_25, 
            sat_26, sat_27, sat_28, sat_29, sat_30,
            sat_31, sat_32, sat_33, sat_34, sat_35,
            sat_36, sat_37, sat_38, sat_39, sat_40,
            unsat_21, unsat_22, unsat_23, unsat_24, unsat_25,
            unsat_26, unsat_27, unsat_28, unsat_29, unsat_30,
            unsat_31, unsat_32, unsat_33, unsat_34, unsat_35,
            unsat_36, unsat_37, unsat_38, unsat_39, unsat_40)

# reshape testing matrix  
test_data <- as.matrix(test_data)
test_array <- array(data = do.call(cbind, test_data), dim = c(length(test_data), dim(test_data[[1]]), 1)) 

# Testing Labels - 
test_label <- replicate(40, 1)
test_label <- t(test_label)
test_label[21:40] = 0
test_label <- t(test_label)
#test_label <- to_categorical(test_label)

  

# instances, rows, columns, depth
matrix_shape <- c(40, 218, 50, 1) 
```

# Compile CNN: 
```{r}
CNN <- keras_model_sequential()

CNN %>%
  
  #Layer 1 - Reduce the Scale of Input
  layer_conv_2d(filters = 32, kernel_size = c(25,25), strides = c(1, 1),
                activation = 'relu', input_shape = c(218,50,1)) %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_dropout(rate = 0.25) %>%

  # Layer 2
  layer_conv_2d(filters = 64, kernel_size = c(5,5),
                strides = c(1, 1), activation = 'relu') %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_dropout(rate = 0.25) %>%

  # Layer 3
  layer_conv_2d(filters = 128, kernel_size = c(3,3),
                strides = c(1, 1), activation = 'relu') %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_dropout(rate = 0.25) %>%
  
  # Fully Connected Layer - Compute Scores
  layer_flatten() %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
  
  # Compile CNN Model
CNN %>% compile(
    optimizer = "adam",
    loss = "sparse_categorical_crossentropy",
    metrics = "accuracy"
    )
```

# Train and Predict CNN: 
```{r}
# Fit CNN 
CNN %>% fit(train_array, train_label,
            epochs = 15,
            batch_size = 13,
            verbose = 2, 
            validation_data = list(test_array, test_label))

# Accuracy Plot
accuracy <- CNN %>% evaluate(test_array, test_label, verbose = 0)
print(accuracy)

```

# Functions to Process Data: 
```{r}

#Define General Matrix: 
general_matrix = matrix(nrow = 218, ncol = 50)
general_matrix = matrix(0L, nrow = dim(general_matrix)[1], ncol = dim(general_matrix)[2]) 

# Transform Formula to Sparse Matrix
transform <- function(m)
{
  # create a formula matrix
  m1 = as.matrix(m)
  m1 = do.call(rbind, m1)
  
  # place formula matrix in general matrix
  lst = list(m1, general_matrix)
  m1 = as.matrix(bdiag(lst))
  m1 = m1[-219:-436, -51:-53]
  
  #distribute variables 
  for(i in 1:218)
  {
    for(k in 1:3)
    {
      if(m1[i, k] < 0)
      {
        j = abs(m1[i, k])
        
        if(m1[i, j] == 0)
        {
          m1[i, j] = -j
        }
        else if(m1[i, j] != 0)
        {
          if(m1[i, j] < 0)
          {
            g = abs(m1[i,j])
            m1[i, g] = -g
            m1[i, j] = -j
          }
          else if(m1[i, j] > 0)
          {
            g = m1[i, j]
            m1[i, g] = g
            m1[i, j] = -j
          }
        }
        
        if(j > 3 && m1[i, k] == -j)
        {
          m1[i, k] = 0
        }
      }
      else if(m1[i, k] > 0)
      {
        j = m1[i, k]
        
        if(m1[i, j] == 0)
        {
          m1[i, j] = j
        }
        else if(m1[i, j] != 0)
        {
          if(m1[i, j] < 0)
          {
            g = abs(m1[i,j])
            m1[i, g] = -g
            m1[i, j] = j
          }
          else if(m1[i, j] > 0)
          {
            g = m1[i, j]
            m1[i, g] = g
            m1[i, j] = j
          }
        }
        
        if(j > 3 && m1[i, k] == j)
        {
          m1[i, k] = 0 
        }
      }
    }
  }
  
  # Delete Duplicates: 
  for(i in 1:218)
  {
    for(k in 1:3)
    {
      if(abs(m1[i,k]) != k)
      {
        m1[i,k] = 0
      }
    }
  }
  
  # Set to -1, 1: 
  for(i in 1:218)
  {
    for(k in 1:50)
    {
      if(m1[i,k] > 0)
      {
        m1[i,k] = 1
      }
      else if(m1[i,k] < 0)
      {
        m1[i,k] = -1
      }
    }
  }
  
  return(m1)
}


# Verify Literal Count in Matrix
count <- function(n)
{
m <- n
count = 0 
for(i in 1:218)
{
  for(k in 1:50)
  {
    if(m[i,k] != 0)
    {
      count = count + 1
    }
  }
}
return(count)
}
```


